### ISSUE TITLE
GL504GS having a problem

### ISSUE THREAD

**Issue by 52PengUin** [ShivangDave/Asus_ROG_Strix_II_GL504GW_Clover#1]
My computer is Asus ROG Strix II GL504GS with Nvdia 1070 graphis card. Considering the slight difference between 504GW and 504GS, I wanted to intsall the macOS by using your EFI. But when I tried to install the macOS 10.13.6, a white apple icon and the progress bar will appear in an instant and then the computer restart automatically. Can I adjust some of the configs associated with the graphis card to make it suitable for GL504GS ? I would appreciate it if you could help me.

**Comment by ShivangDave** [comment]
Are you using Clover or Opencore installation?
You may need to update clover to the newest version.

**Comment by ShivangDave** [comment]
I don't have any gpu settings for RTX 2070.
You did replace the DSDT with your own right?

**Comment by acnicu** [comment]
I had a brief look at your EFI folder and it appears you switched the internal Wi-Fi with another one. Am I correct?

**Comment by acnicu** [comment]
I have the same laptop and just finished the setup and now I'm going through the stuff to see what it's still to be fixed.

**Comment by ShivangDave** [comment]
Yes
I switched to Dell DW1820A which works with minimal fixes

**Comment by acnicu** [comment]
Did my own thing and I have problems with the touchpad (a bad config.plist edit hopefully) and I can't shut it down (so improper power management?) as it's stuck on a black screen with text when I do that. That's the things I need to fix (bluetooth reports that it's working, though I wouldn't know for sure as I haven't tried it). I'll try to study your files some more and see what I can do to make it work - what am I doing wrong and how to fix stuff.

**Comment by 52PengUin** [comment]
I use your EFI and replace the DSDT. However, it shows a prohibition sign and I haven't found the cause yet.

**Comment by ShivangDave** [comment]
@acnicu yeah I'd probably check boot logs to see if any of the tables are failing to load.
@52PengUin This folder is for 10.15.4 or 10.15.5 I'm not sure if the new update broke anything.

**Comment by 52PengUin** [comment]
Thanks a lot. I find that opencore seems not suitable for 10.13 so I use a clover and finally enter the system.

**Comment by ShivangDave** [comment]
Aight @52PengUin 
I'm going the close the issue since you were able to boot.
Feel free to open a new one if there's anything.
